name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check for large files
        uses: actionsdesk/lfs-warning@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filesizelimit: "524288" # 500 KB

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          create_virtualenvs: true

      - name: Set poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry config --list

      - name: Cache poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Verify code quality
        run: |
          poetry run black --config pyproject.toml . --check
          poetry run flake8 --config .flake8

      - name: Run pytest
        env:
          BANANO_HTTP_PROVIDER_URI: ${{ secrets.BANANO_HTTP_PROVIDER_URI }}
        run: poetry run pytest -v

  build-docs:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          create_virtualenvs: true

      - name: Set poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry config --list

      - name: Cache poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      # enforce poetry sphinx instead of ubuntu:latest
      - name: Set sphinx path
        run: echo "::set-env name=SPHINXBUILD::$(poetry env info --path)/bin/sphinx-build"

      - name: Build docs
        run: cd docs/ && make html

      - name: Disable jekyll builds
        run: touch docs/_build/html/.nojekyll

      - name: Upload docs as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html
          path: docs/_build/html

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest

    steps:
      - name: Download docs as artifacts
        uses: actions/download-artifact@v1
        with:
          name: html

      - name: Deploy github pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: html
          commit_message: ${{ github.event.head_commit.message }}
          user_name: "bananopy-actions"
          user_email: "bananopy-actions@bots.noreply.github.com"
